package main;

import engine.events.EventType;

public enum JDEventType implements EventType {
    HELLO_WORLD,
    PONG,

    MENU_ENTERED,
    MENU_EXITED,

    MAIN_SCENE_ENTERED,
    MAIN_SCENE_EXITED,

    ROUNDSELECT_ENTERED,
    ROUNDSELECT_EXITED,

    MARKET_ENTERED,
    MARKET_EXITED,

    PLAY_PHASE_ENTERED, 
    PLAY_PHASE_EXITED,

    //PLAYPHASE
    INITIAL_HAND_DRAWN, //HAND
    TILE_DISCARDED, //TILE
    TILE_DRAWN, //TILE
    HAND_EVALUATED, //
    ROUND_WON, 
    HAND_CHANGED, //ARRAY
    SCORED, //WINCONTEXT

    GAME_LOSS,

    TENPAI_AVAILABLE, //LIST<LIST<TILEPRIMITIVE>>, i.e. TILE_INDEX -> LIST<TILES>
    TSUMO_AVAILABLE,

    //HEROS



    WINCONTEXT_ANALYZED,
    BEFORE_YAKU,
    AFTER_YAKU,
    BEFORE_SCORE,
    AFTER_SCORE, 
    NEW_ROTATION, 
    MONEY_SPENT, 
    MONEY_SPEND_FAILED, 
    MP_SPENT, 
    MP_SPENT_FAILED, 
    MP_UPDATED, 
    MAX_MP_DECREASED, 
    MAX_MP_INCREASED, 
    MP_INCREASED, 
    MONEY_INCREASED, 
    DISCARD_QUEUE_EFFECT_APPLIED, 
    TRADING_CARD_ADDED, HERO_ADDED, HERO_REMOVED_AT_INDEX, DECK_SHUFFLED, HAND_DUMPED, CHECK_DORA,
}
